apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
  namespace: app
spec:
  selector:
    app: go-app
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
